version: '3'
services:
  web-wallet:
    container_name: web-wallet
    build: build/php
    mem_limit: 512m
    restart: always
    volumes:
      - "./app:/var/www/html/wallet/app"
      - "./logs:/var/log"
      - "./conf/php/php.ini:/etc/php5/apache2/php.ini"
      - "./conf/apache/sites-available:/etc/apache2/sites-available/"
      - "./logs:/var/log/apache2/"
    ports:
     - 80:80
     - 443:443
    links:
         - db-wallet
    expose:
      - 80
      - 443
    networks:
      - wallet-compose-network

  db-wallet:
    container_name: db-wallet
    image: 'mysql:5.7'
    entrypoint:
      - /entrypoint.sh
      - '--character-set-server=utf8'
      - '--collation-server=utf8_general_ci'
      - '--sql-mode=NO_AUTO_CREATE_USER'
    command: '--default-authentication-plugin=mysql_native_password --disable-partition-engine-check'
    restart: always
    volumes:
      - './mysql-dump/wallet.sql:/docker-entrypoint-initdb.d/wallet.sql'
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: bTyPl7Zd6EJD0OTv
      MYSQL_DATABASE: 'wallet'
      MYSQL_USER: 'wallet'
      MYSQL_PASSWORD: bTyPl7Zd6EJD0OTv
      MYSQL_ROOT_HOST: '%'
    networks:
      - wallet-compose-network

networks: 
  wallet-compose-network:
    driver: bridge
