version: '3'
services:
  app-wallet:
    container_name: app-wallet
    #image: nginx:latest
    build: build/php56-apache-mysql
    mem_limit: 512m
    restart: always
    volumes:
      - "./app:/var/www/html/wallet/app"
      - "./logs:/var/log"
    #environment:
    #  # NGINX-PROXY ENVIRONMENT VARIABLES: UPDATE ME
    #  - VIRTUAL_HOST=wallet.com.br 
    #  - VIRTUAL_PORT=80
    #  - LETSENCRYPT_HOST=wallet.com.br 
    #  - LETSENCRYPT_EMAIL=admin@wallet.com.br
    #  # /END NGINX-PROXY ENVIRONMENT VARIABLES
    ports:
     - 80:80
     - 443:443
    links:
        - db-wallet
    expose:
      - 80
      - 443
    networks:
      - mysql-compose-network

  db-wallet:
    container_name: db-wallet
    image: 'mysql:5.7'
    entrypoint:
      - /entrypoint.sh
      - '--character-set-server=utf8'
      - '--collation-server=utf8_general_ci'
      - '--sql-mode=NO_AUTO_CREATE_USER'
    command: '--default-authentication-plugin=mysql_native_password --disable-partition-engine-check'
    restart: always
    volumes:
      - './mysql-dump/wallet.sql:/docker-entrypoint-initdb.d/wallet.sql'
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: 'wallet'
      MYSQL_DATABASE: 'wallet'
      MYSQL_USER: 'wallet'
      MYSQL_PASSWORD: 'wallet'
      MYSQL_ROOT_HOST: '%'
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge
